### ISSUE TITLE
Run under Node 18, Error in Strapi example app Foodadvisor

### ISSUE THREAD

**Issue by xiaoyu1985ban** [offset-dev/strapi-calendar#30]
After I change the Local from en to **ja,** got the following error.

```
[2023-05-30 15:35:10.810] http: GET /i18n/locales (63 ms) 200
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: May 30, 2023, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (D:\99_headless_cms_temp\strapi_front\foodadvisor\api\node_modules\moment\moment.js:324:25)
    at configFromString (D:\99_headless_cms_temp\strapi_front\foodadvisor\api\node_modules\moment\moment.js:2550:19)
    at configFromInput (D:\99_headless_cms_temp\strapi_front\foodadvisor\api\node_modules\moment\moment.js:2993:13)
    at prepareConfig (D:\99_headless_cms_temp\strapi_front\foodadvisor\api\node_modules\moment\moment.js:2976:13)
    at createFromConfig (D:\99_headless_cms_temp\strapi_front\foodadvisor\api\node_modules\moment\moment.js:2943:44)
    at createLocalOrUTC (D:\99_headless_cms_temp\strapi_front\foodadvisor\api\node_modules\moment\moment.js:3037:16)
    at createLocal (D:\99_headless_cms_temp\strapi_front\foodadvisor\api\node_modules\moment\moment.js:3041:16)
    at hooks (D:\99_headless_cms_temp\strapi_front\foodadvisor\api\node_modules\moment\moment.js:16:29)
    at Object.getData (D:\99_headless_cms_temp\strapi_front\foodadvisor\api\node_modules\@offset-dev\strapi-calendar\server\services\service.js:28:19)
```

Checkout "strapi-calendar\server\services\service.js", I got that
```
    const filters = {
      $and: [
        {
          [config.startField]: {
            $gte: moment(date ?? moment()).startOf('month').subtract(1, 'month').format(),
            $lte: moment(date ?? moment()).endOf('month').add(1, 'month').format(),
          },
        },
      ],
    };
```

also I got the **date** : May 30, 2023

**Comment by xiaoyu1985ban** [comment]
older version of 0.0.8 is used in Foodadvisor.
after update to 0.0.10, everything is ok
