### ISSUE TITLE
Calendar settings appear and disappear in http://localhost:1337/admin/settings/calendar

### ISSUE THREAD

**Issue by juanma1907** [offset-dev/strapi-calendar#50]
When clicking on calendar settings page appears and instantly disappears to a blank page. Already tried deleting cache, build folder and package lock.

**Comment by juanma1907** [comment]
log shows this error:

[2024-09-23 15:07:30.426] error: Cannot destructure property 'kind' of 'strapi2.getModel(...)' as it is undefined.
TypeError: Cannot destructure property 'kind' of 'strapi2.getModel(...)' as it is undefined.
    at Object.findMany (Z:\dev\avi-sietemares-ui\node_modules\@strapi\strapi\dist\services\entity-service\index.js:97:13)
    at Object.<anonymous> (Z:\dev\avi-sietemares-ui\node_modules\@strapi\strapi\dist\services\entity-service\index.js:341:47)
    at Object.findMany (Z:\dev\avi-sietemares-ui\node_modules\@strapi\plugin-i18n\dist\server\index.js:3285:31)
    at proto.<computed> [as findMany] (Z:\dev\avi-sietemares-ui\node_modules\delegates\index.js:40:31)
    at startHandler (Z:\dev\avi-sietemares-ui\node_modules\@offset-dev\strapi-calendar\server\services\service.js:18:27)
    at Object.getData (Z:\dev\avi-sietemares-ui\node_modules\@offset-dev\strapi-calendar\server\services\service.js:67:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.getData (Z:\dev\avi-sietemares-ui\node_modules\@offset-dev\strapi-calendar\server\controllers\controller.js:6:18)
    at async returnBodyMiddleware (Z:\dev\avi-sietemares-ui\node_modules\@strapi\strapi\dist\services\server\compose-endpoint.js:42:18)
    at async policiesMiddleware (Z:\dev\avi-sietemares-ui\node_modules\@strapi\strapi\dist\services\server\policy.js:15:5)
    at async Z:\dev\avi-sietemares-ui\node_modules\@strapi\strapi\dist\services\server\compose-endpoint.js:27:12
    at async serve (Z:\dev\avi-sietemares-ui\node_modules\koa-static\index.js:59:5)
    at async returnBodyMiddleware (Z:\dev\avi-sietemares-ui\node_modules\@strapi\strapi\dist\services\server\compose-endpoint.js:42:18)
    at async policiesMiddleware (Z:\dev\avi-sietemares-ui\node_modules\@strapi\strapi\dist\services\server\policy.js:15:5)
    at async Z:\dev\avi-sietemares-ui\node_modules\@strapi\strapi\dist\services\server\compose-endpoint.js:27:12
    at async Z:\dev\avi-sietemares-ui\node_modules\@strapi\strapi\dist\middlewares\body.js:45:9


and console from devtools shows this error:

main.97a3feee.js:2946 TypeError: Cannot read properties of undefined (reading 'attributes')
    at 8273.36cf4fb4.chunk.js:44:771
    at Fs (main.97a3feee.js:2946:25612)
    at Ap (main.97a3feee.js:2946:44725)
    at K4 (main.97a3feee.js:2946:38616)
    at Sc (main.97a3feee.js:2944:3353)
    at pp (main.97a3feee.js:2946:43517)
    at fp (main.97a3feee.js:2946:42456)
    at Hp (main.97a3feee.js:2946:37696)
    at le (main.97a3feee.js:3038:1655)
    at MessagePort.Se (main.97a3feee.js:3038:2046)
Fp @ main.97a3feee.js:2946
Gf.se.callback @ main.97a3feee.js:2946
di @ main.97a3feee.js:2944
Od @ main.97a3feee.js:2946
Hh @ main.97a3feee.js:2946
Cd @ main.97a3feee.js:2946
pp @ main.97a3feee.js:2946
fp @ main.97a3feee.js:2946
K4 @ main.97a3feee.js:2946
Sc @ main.97a3feee.js:2944
pp @ main.97a3feee.js:2946
fp @ main.97a3feee.js:2946
Hp @ main.97a3feee.js:2946
le @ main.97a3feee.js:3038
Se @ main.97a3feee.js:3038Understand this error
main.97a3feee.js:2944 Uncaught TypeError: Cannot read properties of undefined (reading 'attributes')
    at 8273.36cf4fb4.chunk.js:44:771
    at Fs (main.97a3feee.js:2946:25612)
    at Ap (main.97a3feee.js:2946:44725)
    at K4 (main.97a3feee.js:2946:38616)
    at Sc (main.97a3feee.js:2944:3353)
    at pp (main.97a3feee.js:2946:43517)
    at fp (main.97a3feee.js:2946:42456)
    at Hp (main.97a3feee.js:2946:37696)
    at le (main.97a3feee.js:3038:1655)
    at MessagePort.Se (main.97a3feee.js:3038:2046)

**Comment by LuisRodriguezLD** [comment]
Which version of Strapi are you using?
>Also when trying to create event it shows: Woops! Something went wrong. Please, try again.

This sounds like you have a problem with the database. If you are using sqlite, try deleting the db file

**Comment by LuisRodriguezLD** [comment]
Hello @juanma1907 
I'm closing this issues, please reopen if issue persists
